spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  application:
    name: ride-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
      metadataMap:
        metrics.path: /actuator/prometheus
        health.path: /actuator/health
        management.context-path: /actuator
server:
  port: 8080

logging:
  logstash:
    server: "logstash:5000"
  level:
    root: INFO
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus