version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  escooter-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escooter-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/escooter

volumes:
  mongodb_data:
