package com.escooter;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;


@SpringBootApplication()
@EnableMongoRepositories


public class EScooterManagementSystem {

    public static void main(final String[] args) {

		SpringApplication.run(EScooterManagementSystem.class, args);
    }
}
