spring:
  zipkin:
    base-url: http://zipkin:9411
  data:
    mongodb:
      uri: ${MONGODB_URI}
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    metadataMap:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
server:
  port: 8080

logging:
  logstash:
    server: "logstash:5000"
  level:
    root: INFO


#springdoc:
#  swagger-ui:
#    path: /swagger/users.html
management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  health:
    mongo:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus