http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline/logstash.conf
api:
  ssl:
    enabled: false
xpack:
  management:
    enabled: false
    elasticsearch:
      hosts: ["elasticsearch:9200"]

